# Flask settings
DEFAULT_FLASK_SERVER_NAME = '127.0.0.1'
DEFAULT_FLASK_SERVER_PORT = '5000'
DEFAULT_FLASK_DEBUG = '1'

# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

# ISRGAN client settings
DEFAULT_TF_SERVER_NAME = '3.137.114.159'
DEFAULT_TF_SERVER_PORT = 80
ISRGAN_MODEL_NAME = 'my_model'
ISRGAN_MODEL_SIGNATURE_NAME = 'serving_default'
ISRGAN_MODEL_INPUTS_KEY = 'input_2'
